version: '2'
services:
  my-calculator:
    build:
      dockerfile: Dockerfile
    image: ms-calculator:latest
    ports:
      - 8060-8070:8080
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge